Added test example. Error codes. AHIM_Buffer_SampleFrameSize(). The usual bug fixing.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 5.36  .
+# From configure.in Revision: 5.37  .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52 for AHI 7.0.
 #
@@ -4232,7 +4232,7 @@ EOF
 fi
 done
 
-ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Classes/Common/Makefile.common Classes/AHIRootClass/Makefile Classes/Buffer/Makefile Classes/Processor/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
+ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Classes/test/Makefile Classes/Common/Makefile.common Classes/AHI/Makefile Classes/Buffer/Makefile Classes/Processor/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -4544,8 +4544,9 @@ do
   "AHI-Handler/Makefile" ) CONFIG_FILES="$CONFIG_FILES AHI-Handler/Makefile" ;;
   "AddAudioModes/Makefile" ) CONFIG_FILES="$CONFIG_FILES AddAudioModes/Makefile" ;;
   "Classes/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/Makefile" ;;
+  "Classes/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/test/Makefile" ;;
   "Classes/Common/Makefile.common" ) CONFIG_FILES="$CONFIG_FILES Classes/Common/Makefile.common" ;;
-  "Classes/AHIRootClass/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/AHIRootClass/Makefile" ;;
+  "Classes/AHI/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/AHI/Makefile" ;;
   "Classes/Buffer/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/Buffer/Makefile" ;;
   "Classes/Processor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/Processor/Makefile" ;;
   "Device/Makefile" ) CONFIG_FILES="$CONFIG_FILES Device/Makefile" ;;
@@ -4565,7 +4566,7 @@ do
   "Include/Makefile" ) CONFIG_FILES="$CONFIG_FILES Include/Makefile" ;;
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:4568: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4569: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4811,7 +4812,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4814: creating $ac_file" >&5
+    { echo "$as_me:4815: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4829,7 +4830,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4832: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4833: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4842,7 +4843,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4845: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4846: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4875,8 +4876,9 @@ s,@INSTALL@,$ac_INSTALL,;t t
     AHI-Handler/Makefile ) echo timestamp > stamp-h ;;
     AddAudioModes/Makefile ) echo timestamp > stamp-h ;;
     Classes/Makefile ) echo timestamp > stamp-h ;;
+    Classes/test/Makefile ) echo timestamp > stamp-h ;;
     Classes/Common/Makefile.common ) echo timestamp > stamp-h ;;
-    Classes/AHIRootClass/Makefile ) echo timestamp > stamp-h ;;
+    Classes/AHI/Makefile ) echo timestamp > stamp-h ;;
     Classes/Buffer/Makefile ) echo timestamp > stamp-h ;;
     Classes/Processor/Makefile ) echo timestamp > stamp-h ;;
     Device/Makefile ) echo timestamp > stamp-h ;;
@@ -4930,7 +4932,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4933: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4935: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4941,7 +4943,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4944: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4946: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4954,7 +4956,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4957: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4959: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5071,7 +5073,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5074: $ac_file is unchanged" >&5
+      { echo "$as_me:5076: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
