Implemented gain.ahi-processor.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 5.37  .
+# From configure.in Revision: 5.38  .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52 for AHI 7.0.
 #
@@ -4232,7 +4232,7 @@ EOF
 fi
 done
 
-ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Classes/test/Makefile Classes/Common/Makefile.common Classes/AHI/Makefile Classes/Buffer/Makefile Classes/Processor/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
+ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Classes/test/Makefile Classes/Common/Makefile.common Classes/AHI/Makefile Classes/Buffer/Makefile Classes/GainProcessor/Makefile Classes/Processor/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -4548,6 +4548,7 @@ do
   "Classes/Common/Makefile.common" ) CONFIG_FILES="$CONFIG_FILES Classes/Common/Makefile.common" ;;
   "Classes/AHI/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/AHI/Makefile" ;;
   "Classes/Buffer/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/Buffer/Makefile" ;;
+  "Classes/GainProcessor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/GainProcessor/Makefile" ;;
   "Classes/Processor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/Processor/Makefile" ;;
   "Device/Makefile" ) CONFIG_FILES="$CONFIG_FILES Device/Makefile" ;;
   "Docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES Docs/Makefile" ;;
@@ -4566,7 +4567,7 @@ do
   "Include/Makefile" ) CONFIG_FILES="$CONFIG_FILES Include/Makefile" ;;
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:4569: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4570: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4812,7 +4813,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4815: creating $ac_file" >&5
+    { echo "$as_me:4816: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4830,7 +4831,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4833: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4834: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4843,7 +4844,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4846: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4847: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4880,6 +4881,7 @@ s,@INSTALL@,$ac_INSTALL,;t t
     Classes/Common/Makefile.common ) echo timestamp > stamp-h ;;
     Classes/AHI/Makefile ) echo timestamp > stamp-h ;;
     Classes/Buffer/Makefile ) echo timestamp > stamp-h ;;
+    Classes/GainProcessor/Makefile ) echo timestamp > stamp-h ;;
     Classes/Processor/Makefile ) echo timestamp > stamp-h ;;
     Device/Makefile ) echo timestamp > stamp-h ;;
     Docs/Makefile ) echo timestamp > stamp-h ;;
@@ -4932,7 +4934,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4935: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4937: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4943,7 +4945,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4946: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4948: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4956,7 +4958,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4959: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4961: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5073,7 +5075,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5076: $ac_file is unchanged" >&5
+      { echo "$as_me:5078: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
