Regenerated.

diff --git a/ahi/ahisrc/trunk/configure b/ahi/ahisrc/trunk/configure
--- a/ahi/ahisrc/trunk/configure
+++ b/ahi/ahisrc/trunk/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 5.21  .
+# From configure.in Revision: 5.22  .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -1142,7 +1142,7 @@ case $host in
   : ${CPU="i686"}
   linkerflags="-noixemul -r"
   optflags="-mcpu=${CPU} -O2"
-  asflags="-m${CPU} --defsym CPU=${CPU}"
+  asflags="--defsym CPU=${CPU}"
   resident=""    ;;
  m68k-unknown-amigaos)
   : ${CPU="68020"}
@@ -1162,10 +1162,10 @@ EOF
   asflags="-m${CPU} -mregnames --defsym CPU=${CPU}"
   resident="-mresident32"
  ;;
- i?86-pc-*-aros)
+ i?86-*-aros)
  : ${CPU="i386"}
- optflags="-mcpu=${CPU} -O2"
- asflags="-m${CPU} --defsym CPU=${CPU}"
+ optflags="-mcpu=${CPU} -O2 -fomit-frame-pointer"
+ asflags="--defsym CPU=${CPU} --defsym LITTLE_ENDIAN=1"
  resident=""    ;;
  *)
   { echo "$as_me:1171: WARNING: Unknown architecture!" >&5
@@ -3655,7 +3655,7 @@ EOF
 
 fi
 
-ac_config_files="$ac_config_files Makefile AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/EMU10kx/Makefile Examples/Makefile Examples/Extras/CloneAudioModes/Makefile Include/Makefile"
+ac_config_files="$ac_config_files Makefile AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/EMU10kx/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Extras/CloneAudioModes/Makefile Include/Makefile"
 ac_config_commands="$ac_config_commands default"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -3974,12 +3974,13 @@ do
   "Docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES Docs/Makefile" ;;
   "Drivers/Makefile" ) CONFIG_FILES="$CONFIG_FILES Drivers/Makefile" ;;
   "Drivers/EMU10kx/Makefile" ) CONFIG_FILES="$CONFIG_FILES Drivers/EMU10kx/Makefile" ;;
+  "Drivers/Void/Makefile" ) CONFIG_FILES="$CONFIG_FILES Drivers/Void/Makefile" ;;
   "Examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES Examples/Makefile" ;;
   "Examples/Extras/CloneAudioModes/Makefile" ) CONFIG_FILES="$CONFIG_FILES Examples/Extras/CloneAudioModes/Makefile" ;;
   "Include/Makefile" ) CONFIG_FILES="$CONFIG_FILES Include/Makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:3982: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3983: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4226,7 +4227,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4229: creating $ac_file" >&5
+    { echo "$as_me:4230: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4244,7 +4245,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4247: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4248: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4257,7 +4258,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4260: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4261: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4318,7 +4319,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4321: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4322: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4329,7 +4330,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4332: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4333: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4342,7 +4343,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4345: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4346: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4459,7 +4460,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:4462: $ac_file is unchanged" >&5
+      { echo "$as_me:4463: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
