Made PlayTest build.

diff --git a/ahi/ahisrc/trunk/configure b/ahi/ahisrc/trunk/configure
--- a/ahi/ahisrc/trunk/configure
+++ b/ahi/ahisrc/trunk/configure
@@ -3757,7 +3757,7 @@ EOF
 
 fi
 
-ac_config_files="$ac_config_files Makefile AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Include/Makefile"
+ac_config_files="$ac_config_files Makefile AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Include/Makefile"
 ac_config_commands="$ac_config_commands default"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -4081,12 +4081,13 @@ do
   "Drivers/Filesave/Makefile" ) CONFIG_FILES="$CONFIG_FILES Drivers/Filesave/Makefile" ;;
   "Drivers/Void/Makefile" ) CONFIG_FILES="$CONFIG_FILES Drivers/Void/Makefile" ;;
   "Examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES Examples/Makefile" ;;
+  "Examples/Device/PlayTest/Makefile" ) CONFIG_FILES="$CONFIG_FILES Examples/Device/PlayTest/Makefile" ;;
   "Examples/Extras/CloneAudioModes/Makefile" ) CONFIG_FILES="$CONFIG_FILES Examples/Extras/CloneAudioModes/Makefile" ;;
   "Examples/Low-level/PlaySineEverywhere/Makefile" ) CONFIG_FILES="$CONFIG_FILES Examples/Low-level/PlaySineEverywhere/Makefile" ;;
   "Include/Makefile" ) CONFIG_FILES="$CONFIG_FILES Include/Makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:4089: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4090: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4334,7 +4335,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4337: creating $ac_file" >&5
+    { echo "$as_me:4338: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4352,7 +4353,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4355: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4356: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4365,7 +4366,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4368: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4369: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4426,7 +4427,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4429: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4430: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4437,7 +4438,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4440: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4441: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4450,7 +4451,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4453: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4454: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4567,7 +4568,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:4570: $ac_file is unchanged" >&5
+      { echo "$as_me:4571: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
