Build classes.

diff --git a/ahi/ahisrc/trunk/configure b/ahi/ahisrc/trunk/configure
--- a/ahi/ahisrc/trunk/configure
+++ b/ahi/ahisrc/trunk/configure
@@ -4232,7 +4232,7 @@ EOF
 fi
 done
 
-ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
+ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Classes/Common/Makefile.common Classes/AHIRootClass/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -4544,6 +4544,8 @@ do
   "AHI-Handler/Makefile" ) CONFIG_FILES="$CONFIG_FILES AHI-Handler/Makefile" ;;
   "AddAudioModes/Makefile" ) CONFIG_FILES="$CONFIG_FILES AddAudioModes/Makefile" ;;
   "Classes/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/Makefile" ;;
+  "Classes/Common/Makefile.common" ) CONFIG_FILES="$CONFIG_FILES Classes/Common/Makefile.common" ;;
+  "Classes/AHIRootClass/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/AHIRootClass/Makefile" ;;
   "Device/Makefile" ) CONFIG_FILES="$CONFIG_FILES Device/Makefile" ;;
   "Docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES Docs/Makefile" ;;
   "Drivers/Makefile" ) CONFIG_FILES="$CONFIG_FILES Drivers/Makefile" ;;
@@ -4561,7 +4563,7 @@ do
   "Include/Makefile" ) CONFIG_FILES="$CONFIG_FILES Include/Makefile" ;;
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:4564: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4566: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4807,7 +4809,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4810: creating $ac_file" >&5
+    { echo "$as_me:4812: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4825,7 +4827,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4828: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4830: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4838,7 +4840,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4841: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4843: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4871,6 +4873,8 @@ s,@INSTALL@,$ac_INSTALL,;t t
     AHI-Handler/Makefile ) echo timestamp > stamp-h ;;
     AddAudioModes/Makefile ) echo timestamp > stamp-h ;;
     Classes/Makefile ) echo timestamp > stamp-h ;;
+    Classes/Common/Makefile.common ) echo timestamp > stamp-h ;;
+    Classes/AHIRootClass/Makefile ) echo timestamp > stamp-h ;;
     Device/Makefile ) echo timestamp > stamp-h ;;
     Docs/Makefile ) echo timestamp > stamp-h ;;
     Drivers/Makefile ) echo timestamp > stamp-h ;;
@@ -4922,7 +4926,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4925: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4929: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4933,7 +4937,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4936: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4940: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4946,7 +4950,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4949: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4953: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5063,7 +5067,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5066: $ac_file is unchanged" >&5
+      { echo "$as_me:5070: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
