The Examples source code is now included in the Developer bindist.

diff --git a/ahi/ahisrc/trunk/configure b/ahi/ahisrc/trunk/configure
--- a/ahi/ahisrc/trunk/configure
+++ b/ahi/ahisrc/trunk/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 5.11  .
+# From configure.in Revision: 5.12  .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.
 #
@@ -3340,7 +3340,7 @@ EOF
  ;;
 esac
 
-ac_config_files="$ac_config_files Makefile AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Device/Makefile Docs/Makefile Drivers/EMU10kx/Makefile Examples/Extras/CloneAudioModes/Makefile Include/Makefile"
+ac_config_files="$ac_config_files Makefile AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Device/Makefile Docs/Makefile Drivers/EMU10kx/Makefile Examples/Makefile Examples/Extras/CloneAudioModes/Makefile Include/Makefile"
 ac_config_commands="$ac_config_commands default"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -3658,11 +3658,12 @@ do
   "Device/Makefile" ) CONFIG_FILES="$CONFIG_FILES Device/Makefile" ;;
   "Docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES Docs/Makefile" ;;
   "Drivers/EMU10kx/Makefile" ) CONFIG_FILES="$CONFIG_FILES Drivers/EMU10kx/Makefile" ;;
+  "Examples/Makefile" ) CONFIG_FILES="$CONFIG_FILES Examples/Makefile" ;;
   "Examples/Extras/CloneAudioModes/Makefile" ) CONFIG_FILES="$CONFIG_FILES Examples/Extras/CloneAudioModes/Makefile" ;;
   "Include/Makefile" ) CONFIG_FILES="$CONFIG_FILES Include/Makefile" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:3665: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3666: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -3905,7 +3906,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:3908: creating $ac_file" >&5
+    { echo "$as_me:3909: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -3923,7 +3924,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:3926: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:3927: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -3936,7 +3937,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:3939: error: cannot find input file: $f" >&5
+           { { echo "$as_me:3940: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -3997,7 +3998,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4000: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4001: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4008,7 +4009,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4011: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4012: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4021,7 +4022,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4024: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4025: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4138,7 +4139,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:4141: $ac_file is unchanged" >&5
+      { echo "$as_me:4142: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
