Initial implementations of ahi-lfo.class and tick.ahi-processor.

diff --git a/ahi/ahisrc/trunk/configure b/ahi/ahisrc/trunk/configure
--- a/ahi/ahisrc/trunk/configure
+++ b/ahi/ahisrc/trunk/configure
@@ -4232,7 +4232,7 @@ EOF
 fi
 done
 
-ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Classes/test/Makefile Classes/Common/Makefile.common Classes/AHI/Makefile Classes/Buffer/Makefile Classes/GainProcessor/Makefile Classes/Processor/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
+ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Classes/test/Makefile Classes/Common/Makefile.common Classes/AHI/Makefile Classes/Buffer/Makefile Classes/GainProcessor/Makefile Classes/LFO/Makefile Classes/TickProcessor/Makefile Classes/Processor/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -4549,6 +4549,8 @@ do
   "Classes/AHI/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/AHI/Makefile" ;;
   "Classes/Buffer/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/Buffer/Makefile" ;;
   "Classes/GainProcessor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/GainProcessor/Makefile" ;;
+  "Classes/LFO/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/LFO/Makefile" ;;
+  "Classes/TickProcessor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/TickProcessor/Makefile" ;;
   "Classes/Processor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/Processor/Makefile" ;;
   "Device/Makefile" ) CONFIG_FILES="$CONFIG_FILES Device/Makefile" ;;
   "Docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES Docs/Makefile" ;;
@@ -4567,7 +4569,7 @@ do
   "Include/Makefile" ) CONFIG_FILES="$CONFIG_FILES Include/Makefile" ;;
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:4570: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4572: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4813,7 +4815,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4816: creating $ac_file" >&5
+    { echo "$as_me:4818: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4831,7 +4833,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4834: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4836: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4844,7 +4846,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4847: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4849: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4882,6 +4884,8 @@ s,@INSTALL@,$ac_INSTALL,;t t
     Classes/AHI/Makefile ) echo timestamp > stamp-h ;;
     Classes/Buffer/Makefile ) echo timestamp > stamp-h ;;
     Classes/GainProcessor/Makefile ) echo timestamp > stamp-h ;;
+    Classes/LFO/Makefile ) echo timestamp > stamp-h ;;
+    Classes/TickProcessor/Makefile ) echo timestamp > stamp-h ;;
     Classes/Processor/Makefile ) echo timestamp > stamp-h ;;
     Device/Makefile ) echo timestamp > stamp-h ;;
     Docs/Makefile ) echo timestamp > stamp-h ;;
@@ -4934,7 +4938,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4937: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4941: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4945,7 +4949,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4948: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4952: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4958,7 +4962,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4961: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4965: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5075,7 +5079,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5078: $ac_file is unchanged" >&5
+      { echo "$as_me:5082: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
