Added ResamplerProcessor

diff --git a/ahi/ahisrc/trunk/configure b/ahi/ahisrc/trunk/configure
--- a/ahi/ahisrc/trunk/configure
+++ b/ahi/ahisrc/trunk/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 5.44  .
+# From configure.in Revision: 5.45  .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52 for AHI 7.0.
 #
@@ -4232,7 +4232,7 @@ EOF
 fi
 done
 
-ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Classes/test/Makefile Classes/Common/Makefile.common Classes/AHI/Makefile Classes/Board/Makefile Classes/Buffer/Makefile Classes/Driver/Makefile Classes/LFO/Makefile Classes/Processor/Makefile Classes/AdderProcessor/Makefile Classes/GainProcessor/Makefile Classes/SplitterProcessor/Makefile Classes/TickProcessor/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
+ac_config_files="$ac_config_files AHI/Makefile AHI-Handler/Makefile AddAudioModes/Makefile Classes/Makefile Classes/test/Makefile Classes/Common/Makefile.common Classes/AHI/Makefile Classes/Board/Makefile Classes/Buffer/Makefile Classes/Driver/Makefile Classes/LFO/Makefile Classes/Processor/Makefile Classes/AdderProcessor/Makefile Classes/GainProcessor/Makefile Classes/ResamplerProcessor/Makefile Classes/SplitterProcessor/Makefile Classes/TickProcessor/Makefile Device/Makefile Docs/Makefile Drivers/Makefile Drivers/AROS/Makefile Drivers/Common/Makefile.common Drivers/Device/Makefile Drivers/EMU10kx/Makefile Drivers/Filesave/Makefile Drivers/Void/Makefile Examples/Makefile Examples/Device/PlayTest/Makefile Examples/Extras/CloneAudioModes/Makefile Examples/Low-level/PlaySineEverywhere/Makefile Examples/Low-level/ScanAudioModes/Makefile Include/Makefile Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -4554,6 +4554,7 @@ do
   "Classes/Processor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/Processor/Makefile" ;;
   "Classes/AdderProcessor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/AdderProcessor/Makefile" ;;
   "Classes/GainProcessor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/GainProcessor/Makefile" ;;
+  "Classes/ResamplerProcessor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/ResamplerProcessor/Makefile" ;;
   "Classes/SplitterProcessor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/SplitterProcessor/Makefile" ;;
   "Classes/TickProcessor/Makefile" ) CONFIG_FILES="$CONFIG_FILES Classes/TickProcessor/Makefile" ;;
   "Device/Makefile" ) CONFIG_FILES="$CONFIG_FILES Device/Makefile" ;;
@@ -4573,7 +4574,7 @@ do
   "Include/Makefile" ) CONFIG_FILES="$CONFIG_FILES Include/Makefile" ;;
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:4576: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:4577: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4819,7 +4820,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4822: creating $ac_file" >&5
+    { echo "$as_me:4823: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4837,7 +4838,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4840: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4841: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4850,7 +4851,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4853: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4854: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4893,6 +4894,7 @@ s,@INSTALL@,$ac_INSTALL,;t t
     Classes/Processor/Makefile ) echo timestamp > stamp-h ;;
     Classes/AdderProcessor/Makefile ) echo timestamp > stamp-h ;;
     Classes/GainProcessor/Makefile ) echo timestamp > stamp-h ;;
+    Classes/ResamplerProcessor/Makefile ) echo timestamp > stamp-h ;;
     Classes/SplitterProcessor/Makefile ) echo timestamp > stamp-h ;;
     Classes/TickProcessor/Makefile ) echo timestamp > stamp-h ;;
     Device/Makefile ) echo timestamp > stamp-h ;;
@@ -4946,7 +4948,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4949: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4951: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4957,7 +4959,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4960: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4962: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4970,7 +4972,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4973: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4975: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -5087,7 +5089,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:5090: $ac_file is unchanged" >&5
+      { echo "$as_me:5092: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
