OS4 fixes.

diff --git a/ahi/ahisrc/branches/BRANCH_6/configure b/ahi/ahisrc/branches/BRANCH_6/configure
--- a/ahi/ahisrc/branches/BRANCH_6/configure
+++ b/ahi/ahisrc/branches/BRANCH_6/configure
@@ -3654,83 +3654,6 @@ echo "$as_me: error: \"libm is missing.\" " >&2;}
 fi
 
 
-echo "$as_me:$LINENO: checking for MUI_NewObject in -lmui" >&5
-echo $ECHO_N "checking for MUI_NewObject in -lmui... $ECHO_C" >&6
-if test "${ac_cv_lib_mui_MUI_NewObject+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lmui  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char MUI_NewObject ();
-int
-main ()
-{
-MUI_NewObject ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_mui_MUI_NewObject=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-ac_cv_lib_mui_MUI_NewObject=no
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_mui_MUI_NewObject" >&5
-echo "${ECHO_T}$ac_cv_lib_mui_MUI_NewObject" >&6
-if test $ac_cv_lib_mui_MUI_NewObject = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define HAVE_LIBMUI 1
-_ACEOF
-
-  LIBS="-lmui $LIBS"
-
-else
-  { echo "$as_me:$LINENO: WARNING: \"Who cares?\" " >&5
-echo "$as_me: WARNING: \"Who cares?\" " >&2;}
-fi
-
-
 echo "$as_me:$LINENO: checking for DOSBase in -lauto" >&5
 echo $ECHO_N "checking for DOSBase in -lauto... $ECHO_C" >&6
 if test "${ac_cv_lib_auto_DOSBase+set}" = set; then
@@ -3878,6 +3801,83 @@ if test $ac_cv_lib_raauto_LayoutBase = yes; then
 _ACEOF
 
   LIBS="-lraauto $LIBS"
+
+else
+  { echo "$as_me:$LINENO: WARNING: \"Who cares?\" " >&5
+echo "$as_me: WARNING: \"Who cares?\" " >&2;}
+fi
+
+
+echo "$as_me:$LINENO: checking for MUI_NewObject in -lmui" >&5
+echo $ECHO_N "checking for MUI_NewObject in -lmui... $ECHO_C" >&6
+if test "${ac_cv_lib_mui_MUI_NewObject+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmui  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char MUI_NewObject ();
+int
+main ()
+{
+MUI_NewObject ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mui_MUI_NewObject=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_mui_MUI_NewObject=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mui_MUI_NewObject" >&5
+echo "${ECHO_T}$ac_cv_lib_mui_MUI_NewObject" >&6
+if test $ac_cv_lib_mui_MUI_NewObject = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBMUI 1
+_ACEOF
+
+  LIBS="-lmui $LIBS"
 
 else
   { echo "$as_me:$LINENO: WARNING: \"Who cares?\" " >&5
